name: Deploy Collector to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          printf '%s\n' "${{ secrets.CI_CD }}" > id_ed25519
          chmod 600 id_ed25519

      - name: Test SSH connection (debug)
        run: |
          ssh -vvv -i id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} echo "✅ SSH connected"

      - name: Deploy collector to server
        run: |
          ssh -i id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash -s' << 'EOF'
            set -e
            cd /home/sofa/analytics
            echo "Starting collector deployment..."
            docker compose build collector
            docker compose up -d --no-deps --build collector
            echo "Collector deployed successfully."
          EOF

      - name: Cleanup
        run: rm -f id_ed25519
